export const FETCH_COMPANY_DETAILS_REQUEST = 'FETCH_COMPANY_DETAILS_REQUEST';
export const FETCH_COMPANY_DETAILS_SUCCESS = 'FETCH_COMPANY_DETAILS_SUCCESS';
export const FETCH_COMPANY_STOCK_INFO_REQUEST = 'FETCH_COMPANY_STOCK_INFO_REQUEST';
export const FETCH_COMPANY_STOCK_INFO_SUCCESS = 'FETCH_COMPANY_STOCK_INFO_SUCCESS';
export const ADD_FAVOURITE_COMPANY = 'ADD_FAVOURITE_COMPANY';
export const REMOVE_FAVOURITE_COMPANY = 'REMOVE_FAVOURITE_COMPANY';
export const SET_SELECTED_COMPANY = 'SET_SELECTED_COMPANY';

export interface BaseAction {
    type: string;
    payload?: any;
}